### ISSUE TITLE
XML layout for Login Activity

### ISSUE THREAD

**Issue by aarav0012** [bsoc-bitbyte/DigiGate24#2]
## Description
Create a XML layout for login activity based on the design specifications given in [Readme](https://github.com/bsoc-bitbyte/DigiGate/blob/main/README.md#design) file.

### Points to be consider:
1. Use Constraint Layout.
2. The layout should follow the general design specifications with reasonable padding and margin values chosen by the contributor.

### Describe the solution you'd like

I would like to have an XML layout file (`res/layout/activity_login.xml`) for the Login Activity that includes all the necessary UI elements as described above. The layout should:

 The XML layout should be implemented in `res/layout/activity_login.xml`.
- The layout should match the general design specifications provided in the README file.
- The layout should use appropriate padding and margin values chosen by the contributor.
- The layout should be visually consistent with the design mockup provided in the README file.

**Comment by madhavs004** [comment]
@aarav0012 I would like to contribute to this layout.
I will use Constraint Layout as mentioned .I will create a drawable resource file and create custom items for the rounded edit texts and buttons which I will link in the XML layout file .I will use use android: drawableStart inside the email and password EditTexts to add the icons and then create padding in the drawable resource file so that it matches the Figma design. I will use TextViews to display the Login and DigiGate text with suitable font from the Figma file.
Thanks.

**Comment by aarav0012** [comment]
@madhavs004 you can work on this
