### ISSUE TITLE
XML Layout for SignUp Activity

### ISSUE THREAD

**Issue by aarav0012** [bsoc-bitbyte/DigiGate24#3]
### Is your feature request related to a problem? Please describe.

Create a XML layout for sign up activity based on the design specifications given in [Readme](https://github.com/bsoc-bitbyte/DigiGate/blob/main/README.md#design) file.

### Points to be consider:
1. Use Constraint Layout.
2. The layout should follow the general design specifications with reasonable padding and margin values chosen by the contributor.

### Describe the solution you'd like

I would like to have an XML layout file (`res/layout/activity_sign_up.xml`) for the SignUp Activity that includes all the necessary UI elements as described above. The layout should:

 The XML layout should be implemented in `res/layout/activity_sign_up.xml`.
- The layout should match the general design specifications provided in the README file.
- The layout should use appropriate padding and margin values chosen by the contributor.
- The layout should be visually consistent with the design mockup provided in the README file.

**Comment by AyushNarsian** [comment]
@aarav0012 Please assign me this issue. I will use a ConstraintLayout. Add TextView for titles and labels, and EditText for input fields with custom drawables for styling. Include a Button for submission. Adjust colors, padding, and margins as needed.

**Comment by sujalagrawal2** [comment]
@aarav0012 I'd like to take on this issue. My approach will be to add relative layout (so that I can create overlap design ) and inside it I will add  card view (for rounded corner) and inside it I will use constraint layout (so that layout is responsive). I will use TextView, EditText (for input) ,buttons. I will edit the EditView by making custom EditView in drawable.  I will follow specified naming convention for each view group ID.
Please assign it to me.
Thank You.

**Comment by aarav0012** [comment]
@AyushNarsian you can work on this
