### ISSUE TITLE
XML layout for User QR code

### ISSUE THREAD

**Issue by aarav0012** [bsoc-bitbyte/DigiGate24#6]
create an XML layout of User QR code activity based on the design given in [Figma](https://www.figma.com/design/kKT5N7cP7FYCwyMUMGOoaa/DigiGate?node-id=0-1&t=pzQtJ65GNlIh5yhQ-0)

Your layout must follow these guidelines :
1. Use Constraint Layout to ensure the layout is responsive to all screen sizes.
2. Adhere to the given Figma design
3. Follow the specified naming convention for each view group ID to maintain consistency and clarity.

**Comment by sujalagrawal2** [comment]
@aarav0012 I would like to work on this issue. I will use constraint layout and inside it I will add TextView , ImageView and ImageButton . I will follow the naming convention and give proper margins(according to the figma ).
Thank You

**Comment by AyushNarsian** [comment]
@aarav0012 Sir I would like to work on this issue. I will use Figma as reference and use constraint layout and in it i will use TextView, image view and further specific constraints to bind the elements with each other and use string resources instead of hardcoded strings ,all the dimensions would be in the multiple of 4 and the required colors would be added in colors xml file.
Thank You!

**Comment by zephyr004** [comment]
Maintainer @aarav0012,
I would like to work on the issue regarding the User QR code activity. To create the XML layout based on the design given in Figma, I will use the ConstraintLayout as mentioned. For displaying the title and any explanatory text I will use TextView and ImageView to display the QR code image.
I will follow the specified guidelines and also ensure proper alignment, styling, and spacing of the views.
Thankyou.

**Comment by aarav0012** [comment]
@sujalagrawal2 you can work on this
